// Shipping Rate Calculator
// Calculate shipping rates by weight, dimensions, zone, and carrier with support for domestic and international freight.
// Auto-generated by @ph-itdev/logistics-pipeline


const WEIGHT_BREAKS = [
  { min: 0, max: 1, rate: 5.99 },
  { min: 1, max: 5, rate: 8.99 },
  { min: 5, max: 20, rate: 12.99 },
  { min: 20, max: 70, rate: 18.99 },
  { min: 70, max: 150, rate: 28.99 },
];

const ZONE_MULTIPLIERS = { local: 1.0, regional: 1.3, national: 1.8, international: 3.2 };

function getWeightRate(weightLbs) {
  const tier = WEIGHT_BREAKS.find(b => weightLbs >= b.min && weightLbs < b.max);
  if (!tier) throw new Error(`Weight ${weightLbs}lbs exceeds max supported (150lbs)`);
  return tier.rate;
}

function calculateShipping({ weight, dimensions, zone = 'national', carrier = 'standard' }) {
  if (!weight || weight <= 0) throw new Error('Weight must be positive');
  const { length = 0, width = 0, height = 0 } = dimensions || {};
  const dimensionalWeight = (length * width * height) / 139;
  const billableWeight = Math.max(weight, dimensionalWeight);
  const baseRate = getWeightRate(billableWeight);
  const multiplier = ZONE_MULTIPLIERS[zone] || ZONE_MULTIPLIERS.national;
  const carrierSurcharge = carrier === 'express' ? 1.5 : carrier === 'overnight' ? 2.5 : 1.0;
  const total = +(baseRate * multiplier * carrierSurcharge).toFixed(2);
  return { baseRate, multiplier, carrierSurcharge, billableWeight: +billableWeight.toFixed(1), total };
}



// ─── Error handling utilities ────────────────────────────────────────────────
class LogisticsError extends Error {
  constructor(message, code, details = {}) {
    super(message);
    this.name = 'LogisticsError';
    this.code = code;
    this.details = details;
    this.timestamp = new Date().toISOString();
  }
}

function _logisticsErrorGuard(fn, context = 'unknown') {
  return function(...args) {
    try { return fn.apply(this, args); }
    catch (e) { throw new LogisticsError(`${context}: ${e.message}`, 'OPERATION_FAILED', { args: args.length, cause: e.message }); }
  };
}


// ─── Auto-generated utility helpers ──────────────────────────────────────────
function _logisticsHelpers() {
  return {
    timestamp: () => new Date().toISOString(),
    uuid: () => 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, c => {
      const r = Math.random() * 16 | 0;
      return (c === 'x' ? r : (r & 0x3 | 0x8)).toString(16);
    }),
    sleep: (ms) => new Promise(r => setTimeout(r, ms)),
    retry: async (fn, maxAttempts = 3, delayMs = 1000) => {
      for (let i = 0; i < maxAttempts; i++) {
        try { return await fn(); } catch (e) { if (i === maxAttempts - 1) throw e; await new Promise(r => setTimeout(r, delayMs * (i + 1))); }
      }
    },
    clamp: (val, min, max) => Math.min(Math.max(val, min), max),
    chunk: (arr, size) => Array.from({ length: Math.ceil(arr.length / size) }, (_, i) => arr.slice(i * size, i * size + size)),
  };
}

module.exports = { calculateShipping, getWeightRate, WEIGHT_BREAKS, ZONE_MULTIPLIERS };
